#!/bin/bash
# install-git-hook.sh - Installs commit-msg git hook to enforce Conventional Commits.

TARGET_DIR="${1:-.}"

if [ ! -d "$TARGET_DIR/.git" ]; then
  echo "Error: $TARGET_DIR is not a git repository (missing .git directory)."
  exit 1
fi

HOOK_FILE="$TARGET_DIR/.git/hooks/commit-msg"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINTER_PATH="$SCRIPT_DIR/commit-lint.sh"

cat <<EOF > "$HOOK_FILE"
#!/bin/bash
# Automatically generated by conventional-commits skill
"$LINTER_PATH" "\$1"
EOF

chmod +x "$HOOK_FILE"
echo "✔ Installed commit-msg git hook successfully at $HOOK_FILE"
